package com.bll.lnkstudy.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bll.lnkstudy.mvp.model.Book;
import com.bll.lnkstudy.mvp.model.CourseBean;
import com.bll.lnkstudy.mvp.model.DateEvent;
import com.bll.lnkstudy.mvp.model.Homework;
import com.bll.lnkstudy.mvp.model.HomeworkContent;
import com.bll.lnkstudy.mvp.model.HomeworkType;
import com.bll.lnkstudy.mvp.model.Note;
import com.bll.lnkstudy.mvp.model.NoteBook;
import com.bll.lnkstudy.mvp.model.RecordBean;

import com.bll.lnkstudy.greendao.BookDao;
import com.bll.lnkstudy.greendao.CourseBeanDao;
import com.bll.lnkstudy.greendao.DateEventDao;
import com.bll.lnkstudy.greendao.HomeworkDao;
import com.bll.lnkstudy.greendao.HomeworkContentDao;
import com.bll.lnkstudy.greendao.HomeworkTypeDao;
import com.bll.lnkstudy.greendao.NoteDao;
import com.bll.lnkstudy.greendao.NoteBookDao;
import com.bll.lnkstudy.greendao.RecordBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDaoConfig;
    private final DaoConfig courseBeanDaoConfig;
    private final DaoConfig dateEventDaoConfig;
    private final DaoConfig homeworkDaoConfig;
    private final DaoConfig homeworkContentDaoConfig;
    private final DaoConfig homeworkTypeDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig noteBookDaoConfig;
    private final DaoConfig recordBeanDaoConfig;

    private final BookDao bookDao;
    private final CourseBeanDao courseBeanDao;
    private final DateEventDao dateEventDao;
    private final HomeworkDao homeworkDao;
    private final HomeworkContentDao homeworkContentDao;
    private final HomeworkTypeDao homeworkTypeDao;
    private final NoteDao noteDao;
    private final NoteBookDao noteBookDao;
    private final RecordBeanDao recordBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        courseBeanDaoConfig = daoConfigMap.get(CourseBeanDao.class).clone();
        courseBeanDaoConfig.initIdentityScope(type);

        dateEventDaoConfig = daoConfigMap.get(DateEventDao.class).clone();
        dateEventDaoConfig.initIdentityScope(type);

        homeworkDaoConfig = daoConfigMap.get(HomeworkDao.class).clone();
        homeworkDaoConfig.initIdentityScope(type);

        homeworkContentDaoConfig = daoConfigMap.get(HomeworkContentDao.class).clone();
        homeworkContentDaoConfig.initIdentityScope(type);

        homeworkTypeDaoConfig = daoConfigMap.get(HomeworkTypeDao.class).clone();
        homeworkTypeDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        noteBookDaoConfig = daoConfigMap.get(NoteBookDao.class).clone();
        noteBookDaoConfig.initIdentityScope(type);

        recordBeanDaoConfig = daoConfigMap.get(RecordBeanDao.class).clone();
        recordBeanDaoConfig.initIdentityScope(type);

        bookDao = new BookDao(bookDaoConfig, this);
        courseBeanDao = new CourseBeanDao(courseBeanDaoConfig, this);
        dateEventDao = new DateEventDao(dateEventDaoConfig, this);
        homeworkDao = new HomeworkDao(homeworkDaoConfig, this);
        homeworkContentDao = new HomeworkContentDao(homeworkContentDaoConfig, this);
        homeworkTypeDao = new HomeworkTypeDao(homeworkTypeDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        noteBookDao = new NoteBookDao(noteBookDaoConfig, this);
        recordBeanDao = new RecordBeanDao(recordBeanDaoConfig, this);

        registerDao(Book.class, bookDao);
        registerDao(CourseBean.class, courseBeanDao);
        registerDao(DateEvent.class, dateEventDao);
        registerDao(Homework.class, homeworkDao);
        registerDao(HomeworkContent.class, homeworkContentDao);
        registerDao(HomeworkType.class, homeworkTypeDao);
        registerDao(Note.class, noteDao);
        registerDao(NoteBook.class, noteBookDao);
        registerDao(RecordBean.class, recordBeanDao);
    }
    
    public void clear() {
        bookDaoConfig.clearIdentityScope();
        courseBeanDaoConfig.clearIdentityScope();
        dateEventDaoConfig.clearIdentityScope();
        homeworkDaoConfig.clearIdentityScope();
        homeworkContentDaoConfig.clearIdentityScope();
        homeworkTypeDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
        noteBookDaoConfig.clearIdentityScope();
        recordBeanDaoConfig.clearIdentityScope();
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public CourseBeanDao getCourseBeanDao() {
        return courseBeanDao;
    }

    public DateEventDao getDateEventDao() {
        return dateEventDao;
    }

    public HomeworkDao getHomeworkDao() {
        return homeworkDao;
    }

    public HomeworkContentDao getHomeworkContentDao() {
        return homeworkContentDao;
    }

    public HomeworkTypeDao getHomeworkTypeDao() {
        return homeworkTypeDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public NoteBookDao getNoteBookDao() {
        return noteBookDao;
    }

    public RecordBeanDao getRecordBeanDao() {
        return recordBeanDao;
    }

}
