package com.bll.lnkstudy.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bll.lnkstudy.mvp.model.AppBean;
import com.bll.lnkstudy.mvp.model.BookBean;
import com.bll.lnkstudy.mvp.model.CourseBean;
import com.bll.lnkstudy.mvp.model.DataUpdateBean;
import com.bll.lnkstudy.mvp.model.DiaryBean;
import com.bll.lnkstudy.mvp.model.FreeNoteBean;
import com.bll.lnkstudy.mvp.model.Note;
import com.bll.lnkstudy.mvp.model.NoteContentBean;
import com.bll.lnkstudy.mvp.model.Notebook;
import com.bll.lnkstudy.mvp.model.RecordBean;
import com.bll.lnkstudy.mvp.model.date.DateEventBean;
import com.bll.lnkstudy.mvp.model.homework.HomeworkBookBean;
import com.bll.lnkstudy.mvp.model.homework.HomeworkContentBean;
import com.bll.lnkstudy.mvp.model.homework.HomeworkPaperBean;
import com.bll.lnkstudy.mvp.model.homework.HomeworkPaperContentBean;
import com.bll.lnkstudy.mvp.model.homework.HomeworkTypeBean;
import com.bll.lnkstudy.mvp.model.painting.PaintingBean;
import com.bll.lnkstudy.mvp.model.painting.PaintingDrawingBean;
import com.bll.lnkstudy.mvp.model.painting.PaintingTypeBean;
import com.bll.lnkstudy.mvp.model.paper.PaperBean;
import com.bll.lnkstudy.mvp.model.paper.PaperContentBean;
import com.bll.lnkstudy.mvp.model.paper.PaperTypeBean;

import com.bll.lnkstudy.greendao.AppBeanDao;
import com.bll.lnkstudy.greendao.BookBeanDao;
import com.bll.lnkstudy.greendao.CourseBeanDao;
import com.bll.lnkstudy.greendao.DataUpdateBeanDao;
import com.bll.lnkstudy.greendao.DiaryBeanDao;
import com.bll.lnkstudy.greendao.FreeNoteBeanDao;
import com.bll.lnkstudy.greendao.NoteDao;
import com.bll.lnkstudy.greendao.NoteContentBeanDao;
import com.bll.lnkstudy.greendao.NotebookDao;
import com.bll.lnkstudy.greendao.RecordBeanDao;
import com.bll.lnkstudy.greendao.DateEventBeanDao;
import com.bll.lnkstudy.greendao.HomeworkBookBeanDao;
import com.bll.lnkstudy.greendao.HomeworkContentBeanDao;
import com.bll.lnkstudy.greendao.HomeworkPaperBeanDao;
import com.bll.lnkstudy.greendao.HomeworkPaperContentBeanDao;
import com.bll.lnkstudy.greendao.HomeworkTypeBeanDao;
import com.bll.lnkstudy.greendao.PaintingBeanDao;
import com.bll.lnkstudy.greendao.PaintingDrawingBeanDao;
import com.bll.lnkstudy.greendao.PaintingTypeBeanDao;
import com.bll.lnkstudy.greendao.PaperBeanDao;
import com.bll.lnkstudy.greendao.PaperContentBeanDao;
import com.bll.lnkstudy.greendao.PaperTypeBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appBeanDaoConfig;
    private final DaoConfig bookBeanDaoConfig;
    private final DaoConfig courseBeanDaoConfig;
    private final DaoConfig dataUpdateBeanDaoConfig;
    private final DaoConfig diaryBeanDaoConfig;
    private final DaoConfig freeNoteBeanDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig noteContentBeanDaoConfig;
    private final DaoConfig notebookDaoConfig;
    private final DaoConfig recordBeanDaoConfig;
    private final DaoConfig dateEventBeanDaoConfig;
    private final DaoConfig homeworkBookBeanDaoConfig;
    private final DaoConfig homeworkContentBeanDaoConfig;
    private final DaoConfig homeworkPaperBeanDaoConfig;
    private final DaoConfig homeworkPaperContentBeanDaoConfig;
    private final DaoConfig homeworkTypeBeanDaoConfig;
    private final DaoConfig paintingBeanDaoConfig;
    private final DaoConfig paintingDrawingBeanDaoConfig;
    private final DaoConfig paintingTypeBeanDaoConfig;
    private final DaoConfig paperBeanDaoConfig;
    private final DaoConfig paperContentBeanDaoConfig;
    private final DaoConfig paperTypeBeanDaoConfig;

    private final AppBeanDao appBeanDao;
    private final BookBeanDao bookBeanDao;
    private final CourseBeanDao courseBeanDao;
    private final DataUpdateBeanDao dataUpdateBeanDao;
    private final DiaryBeanDao diaryBeanDao;
    private final FreeNoteBeanDao freeNoteBeanDao;
    private final NoteDao noteDao;
    private final NoteContentBeanDao noteContentBeanDao;
    private final NotebookDao notebookDao;
    private final RecordBeanDao recordBeanDao;
    private final DateEventBeanDao dateEventBeanDao;
    private final HomeworkBookBeanDao homeworkBookBeanDao;
    private final HomeworkContentBeanDao homeworkContentBeanDao;
    private final HomeworkPaperBeanDao homeworkPaperBeanDao;
    private final HomeworkPaperContentBeanDao homeworkPaperContentBeanDao;
    private final HomeworkTypeBeanDao homeworkTypeBeanDao;
    private final PaintingBeanDao paintingBeanDao;
    private final PaintingDrawingBeanDao paintingDrawingBeanDao;
    private final PaintingTypeBeanDao paintingTypeBeanDao;
    private final PaperBeanDao paperBeanDao;
    private final PaperContentBeanDao paperContentBeanDao;
    private final PaperTypeBeanDao paperTypeBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appBeanDaoConfig = daoConfigMap.get(AppBeanDao.class).clone();
        appBeanDaoConfig.initIdentityScope(type);

        bookBeanDaoConfig = daoConfigMap.get(BookBeanDao.class).clone();
        bookBeanDaoConfig.initIdentityScope(type);

        courseBeanDaoConfig = daoConfigMap.get(CourseBeanDao.class).clone();
        courseBeanDaoConfig.initIdentityScope(type);

        dataUpdateBeanDaoConfig = daoConfigMap.get(DataUpdateBeanDao.class).clone();
        dataUpdateBeanDaoConfig.initIdentityScope(type);

        diaryBeanDaoConfig = daoConfigMap.get(DiaryBeanDao.class).clone();
        diaryBeanDaoConfig.initIdentityScope(type);

        freeNoteBeanDaoConfig = daoConfigMap.get(FreeNoteBeanDao.class).clone();
        freeNoteBeanDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        noteContentBeanDaoConfig = daoConfigMap.get(NoteContentBeanDao.class).clone();
        noteContentBeanDaoConfig.initIdentityScope(type);

        notebookDaoConfig = daoConfigMap.get(NotebookDao.class).clone();
        notebookDaoConfig.initIdentityScope(type);

        recordBeanDaoConfig = daoConfigMap.get(RecordBeanDao.class).clone();
        recordBeanDaoConfig.initIdentityScope(type);

        dateEventBeanDaoConfig = daoConfigMap.get(DateEventBeanDao.class).clone();
        dateEventBeanDaoConfig.initIdentityScope(type);

        homeworkBookBeanDaoConfig = daoConfigMap.get(HomeworkBookBeanDao.class).clone();
        homeworkBookBeanDaoConfig.initIdentityScope(type);

        homeworkContentBeanDaoConfig = daoConfigMap.get(HomeworkContentBeanDao.class).clone();
        homeworkContentBeanDaoConfig.initIdentityScope(type);

        homeworkPaperBeanDaoConfig = daoConfigMap.get(HomeworkPaperBeanDao.class).clone();
        homeworkPaperBeanDaoConfig.initIdentityScope(type);

        homeworkPaperContentBeanDaoConfig = daoConfigMap.get(HomeworkPaperContentBeanDao.class).clone();
        homeworkPaperContentBeanDaoConfig.initIdentityScope(type);

        homeworkTypeBeanDaoConfig = daoConfigMap.get(HomeworkTypeBeanDao.class).clone();
        homeworkTypeBeanDaoConfig.initIdentityScope(type);

        paintingBeanDaoConfig = daoConfigMap.get(PaintingBeanDao.class).clone();
        paintingBeanDaoConfig.initIdentityScope(type);

        paintingDrawingBeanDaoConfig = daoConfigMap.get(PaintingDrawingBeanDao.class).clone();
        paintingDrawingBeanDaoConfig.initIdentityScope(type);

        paintingTypeBeanDaoConfig = daoConfigMap.get(PaintingTypeBeanDao.class).clone();
        paintingTypeBeanDaoConfig.initIdentityScope(type);

        paperBeanDaoConfig = daoConfigMap.get(PaperBeanDao.class).clone();
        paperBeanDaoConfig.initIdentityScope(type);

        paperContentBeanDaoConfig = daoConfigMap.get(PaperContentBeanDao.class).clone();
        paperContentBeanDaoConfig.initIdentityScope(type);

        paperTypeBeanDaoConfig = daoConfigMap.get(PaperTypeBeanDao.class).clone();
        paperTypeBeanDaoConfig.initIdentityScope(type);

        appBeanDao = new AppBeanDao(appBeanDaoConfig, this);
        bookBeanDao = new BookBeanDao(bookBeanDaoConfig, this);
        courseBeanDao = new CourseBeanDao(courseBeanDaoConfig, this);
        dataUpdateBeanDao = new DataUpdateBeanDao(dataUpdateBeanDaoConfig, this);
        diaryBeanDao = new DiaryBeanDao(diaryBeanDaoConfig, this);
        freeNoteBeanDao = new FreeNoteBeanDao(freeNoteBeanDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        noteContentBeanDao = new NoteContentBeanDao(noteContentBeanDaoConfig, this);
        notebookDao = new NotebookDao(notebookDaoConfig, this);
        recordBeanDao = new RecordBeanDao(recordBeanDaoConfig, this);
        dateEventBeanDao = new DateEventBeanDao(dateEventBeanDaoConfig, this);
        homeworkBookBeanDao = new HomeworkBookBeanDao(homeworkBookBeanDaoConfig, this);
        homeworkContentBeanDao = new HomeworkContentBeanDao(homeworkContentBeanDaoConfig, this);
        homeworkPaperBeanDao = new HomeworkPaperBeanDao(homeworkPaperBeanDaoConfig, this);
        homeworkPaperContentBeanDao = new HomeworkPaperContentBeanDao(homeworkPaperContentBeanDaoConfig, this);
        homeworkTypeBeanDao = new HomeworkTypeBeanDao(homeworkTypeBeanDaoConfig, this);
        paintingBeanDao = new PaintingBeanDao(paintingBeanDaoConfig, this);
        paintingDrawingBeanDao = new PaintingDrawingBeanDao(paintingDrawingBeanDaoConfig, this);
        paintingTypeBeanDao = new PaintingTypeBeanDao(paintingTypeBeanDaoConfig, this);
        paperBeanDao = new PaperBeanDao(paperBeanDaoConfig, this);
        paperContentBeanDao = new PaperContentBeanDao(paperContentBeanDaoConfig, this);
        paperTypeBeanDao = new PaperTypeBeanDao(paperTypeBeanDaoConfig, this);

        registerDao(AppBean.class, appBeanDao);
        registerDao(BookBean.class, bookBeanDao);
        registerDao(CourseBean.class, courseBeanDao);
        registerDao(DataUpdateBean.class, dataUpdateBeanDao);
        registerDao(DiaryBean.class, diaryBeanDao);
        registerDao(FreeNoteBean.class, freeNoteBeanDao);
        registerDao(Note.class, noteDao);
        registerDao(NoteContentBean.class, noteContentBeanDao);
        registerDao(Notebook.class, notebookDao);
        registerDao(RecordBean.class, recordBeanDao);
        registerDao(DateEventBean.class, dateEventBeanDao);
        registerDao(HomeworkBookBean.class, homeworkBookBeanDao);
        registerDao(HomeworkContentBean.class, homeworkContentBeanDao);
        registerDao(HomeworkPaperBean.class, homeworkPaperBeanDao);
        registerDao(HomeworkPaperContentBean.class, homeworkPaperContentBeanDao);
        registerDao(HomeworkTypeBean.class, homeworkTypeBeanDao);
        registerDao(PaintingBean.class, paintingBeanDao);
        registerDao(PaintingDrawingBean.class, paintingDrawingBeanDao);
        registerDao(PaintingTypeBean.class, paintingTypeBeanDao);
        registerDao(PaperBean.class, paperBeanDao);
        registerDao(PaperContentBean.class, paperContentBeanDao);
        registerDao(PaperTypeBean.class, paperTypeBeanDao);
    }
    
    public void clear() {
        appBeanDaoConfig.clearIdentityScope();
        bookBeanDaoConfig.clearIdentityScope();
        courseBeanDaoConfig.clearIdentityScope();
        dataUpdateBeanDaoConfig.clearIdentityScope();
        diaryBeanDaoConfig.clearIdentityScope();
        freeNoteBeanDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
        noteContentBeanDaoConfig.clearIdentityScope();
        notebookDaoConfig.clearIdentityScope();
        recordBeanDaoConfig.clearIdentityScope();
        dateEventBeanDaoConfig.clearIdentityScope();
        homeworkBookBeanDaoConfig.clearIdentityScope();
        homeworkContentBeanDaoConfig.clearIdentityScope();
        homeworkPaperBeanDaoConfig.clearIdentityScope();
        homeworkPaperContentBeanDaoConfig.clearIdentityScope();
        homeworkTypeBeanDaoConfig.clearIdentityScope();
        paintingBeanDaoConfig.clearIdentityScope();
        paintingDrawingBeanDaoConfig.clearIdentityScope();
        paintingTypeBeanDaoConfig.clearIdentityScope();
        paperBeanDaoConfig.clearIdentityScope();
        paperContentBeanDaoConfig.clearIdentityScope();
        paperTypeBeanDaoConfig.clearIdentityScope();
    }

    public AppBeanDao getAppBeanDao() {
        return appBeanDao;
    }

    public BookBeanDao getBookBeanDao() {
        return bookBeanDao;
    }

    public CourseBeanDao getCourseBeanDao() {
        return courseBeanDao;
    }

    public DataUpdateBeanDao getDataUpdateBeanDao() {
        return dataUpdateBeanDao;
    }

    public DiaryBeanDao getDiaryBeanDao() {
        return diaryBeanDao;
    }

    public FreeNoteBeanDao getFreeNoteBeanDao() {
        return freeNoteBeanDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public NoteContentBeanDao getNoteContentBeanDao() {
        return noteContentBeanDao;
    }

    public NotebookDao getNotebookDao() {
        return notebookDao;
    }

    public RecordBeanDao getRecordBeanDao() {
        return recordBeanDao;
    }

    public DateEventBeanDao getDateEventBeanDao() {
        return dateEventBeanDao;
    }

    public HomeworkBookBeanDao getHomeworkBookBeanDao() {
        return homeworkBookBeanDao;
    }

    public HomeworkContentBeanDao getHomeworkContentBeanDao() {
        return homeworkContentBeanDao;
    }

    public HomeworkPaperBeanDao getHomeworkPaperBeanDao() {
        return homeworkPaperBeanDao;
    }

    public HomeworkPaperContentBeanDao getHomeworkPaperContentBeanDao() {
        return homeworkPaperContentBeanDao;
    }

    public HomeworkTypeBeanDao getHomeworkTypeBeanDao() {
        return homeworkTypeBeanDao;
    }

    public PaintingBeanDao getPaintingBeanDao() {
        return paintingBeanDao;
    }

    public PaintingDrawingBeanDao getPaintingDrawingBeanDao() {
        return paintingDrawingBeanDao;
    }

    public PaintingTypeBeanDao getPaintingTypeBeanDao() {
        return paintingTypeBeanDao;
    }

    public PaperBeanDao getPaperBeanDao() {
        return paperBeanDao;
    }

    public PaperContentBeanDao getPaperContentBeanDao() {
        return paperContentBeanDao;
    }

    public PaperTypeBeanDao getPaperTypeBeanDao() {
        return paperTypeBeanDao;
    }

}
