package com.bll.lnkstudy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkstudy.utils.greendao.DatePlanConverter;
import com.bll.lnkstudy.utils.greendao.DateWeekConverter;
import java.util.List;

import com.bll.lnkstudy.mvp.model.DateEvent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DATE_EVENT".
*/
public class DateEventDao extends AbstractDao<DateEvent, Long> {

    public static final String TABLENAME = "DATE_EVENT";

    /**
     * Properties of entity DateEvent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property Type = new Property(2, int.class, "type", false, "TYPE");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property DayLong = new Property(4, Long.class, "dayLong", false, "DAY_LONG");
        public final static Property DayLongStr = new Property(5, String.class, "dayLongStr", false, "DAY_LONG_STR");
        public final static Property Explain = new Property(6, String.class, "explain", false, "EXPLAIN");
        public final static Property IsCountdown = new Property(7, boolean.class, "isCountdown", false, "IS_COUNTDOWN");
        public final static Property IsRemind = new Property(8, boolean.class, "isRemind", false, "IS_REMIND");
        public final static Property RemindDay = new Property(9, int.class, "remindDay", false, "REMIND_DAY");
        public final static Property StartTime = new Property(10, Long.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(11, Long.class, "endTime", false, "END_TIME");
        public final static Property StartTimeStr = new Property(12, String.class, "startTimeStr", false, "START_TIME_STR");
        public final static Property EndTimeStr = new Property(13, String.class, "endTimeStr", false, "END_TIME_STR");
        public final static Property CopyCount = new Property(14, Integer.class, "copyCount", false, "COPY_COUNT");
        public final static Property Weeks = new Property(15, String.class, "weeks", false, "WEEKS");
        public final static Property Plans = new Property(16, String.class, "plans", false, "PLANS");
    }

    private final DateWeekConverter weeksConverter = new DateWeekConverter();
    private final DatePlanConverter plansConverter = new DatePlanConverter();

    public DateEventDao(DaoConfig config) {
        super(config);
    }
    
    public DateEventDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DATE_EVENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"TYPE\" INTEGER NOT NULL ," + // 2: type
                "\"TITLE\" TEXT," + // 3: title
                "\"DAY_LONG\" INTEGER," + // 4: dayLong
                "\"DAY_LONG_STR\" TEXT," + // 5: dayLongStr
                "\"EXPLAIN\" TEXT," + // 6: explain
                "\"IS_COUNTDOWN\" INTEGER NOT NULL ," + // 7: isCountdown
                "\"IS_REMIND\" INTEGER NOT NULL ," + // 8: isRemind
                "\"REMIND_DAY\" INTEGER NOT NULL ," + // 9: remindDay
                "\"START_TIME\" INTEGER," + // 10: startTime
                "\"END_TIME\" INTEGER," + // 11: endTime
                "\"START_TIME_STR\" TEXT," + // 12: startTimeStr
                "\"END_TIME_STR\" TEXT," + // 13: endTimeStr
                "\"COPY_COUNT\" INTEGER," + // 14: copyCount
                "\"WEEKS\" TEXT," + // 15: weeks
                "\"PLANS\" TEXT);"); // 16: plans
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DATE_EVENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DateEvent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getType());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        Long dayLong = entity.getDayLong();
        if (dayLong != null) {
            stmt.bindLong(5, dayLong);
        }
 
        String dayLongStr = entity.getDayLongStr();
        if (dayLongStr != null) {
            stmt.bindString(6, dayLongStr);
        }
 
        String explain = entity.getExplain();
        if (explain != null) {
            stmt.bindString(7, explain);
        }
        stmt.bindLong(8, entity.getIsCountdown() ? 1L: 0L);
        stmt.bindLong(9, entity.getIsRemind() ? 1L: 0L);
        stmt.bindLong(10, entity.getRemindDay());
 
        Long startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindLong(11, startTime);
        }
 
        Long endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(12, endTime);
        }
 
        String startTimeStr = entity.getStartTimeStr();
        if (startTimeStr != null) {
            stmt.bindString(13, startTimeStr);
        }
 
        String endTimeStr = entity.getEndTimeStr();
        if (endTimeStr != null) {
            stmt.bindString(14, endTimeStr);
        }
 
        Integer copyCount = entity.getCopyCount();
        if (copyCount != null) {
            stmt.bindLong(15, copyCount);
        }
 
        List weeks = entity.getWeeks();
        if (weeks != null) {
            stmt.bindString(16, weeksConverter.convertToDatabaseValue(weeks));
        }
 
        List plans = entity.getPlans();
        if (plans != null) {
            stmt.bindString(17, plansConverter.convertToDatabaseValue(plans));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DateEvent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getType());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        Long dayLong = entity.getDayLong();
        if (dayLong != null) {
            stmt.bindLong(5, dayLong);
        }
 
        String dayLongStr = entity.getDayLongStr();
        if (dayLongStr != null) {
            stmt.bindString(6, dayLongStr);
        }
 
        String explain = entity.getExplain();
        if (explain != null) {
            stmt.bindString(7, explain);
        }
        stmt.bindLong(8, entity.getIsCountdown() ? 1L: 0L);
        stmt.bindLong(9, entity.getIsRemind() ? 1L: 0L);
        stmt.bindLong(10, entity.getRemindDay());
 
        Long startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindLong(11, startTime);
        }
 
        Long endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(12, endTime);
        }
 
        String startTimeStr = entity.getStartTimeStr();
        if (startTimeStr != null) {
            stmt.bindString(13, startTimeStr);
        }
 
        String endTimeStr = entity.getEndTimeStr();
        if (endTimeStr != null) {
            stmt.bindString(14, endTimeStr);
        }
 
        Integer copyCount = entity.getCopyCount();
        if (copyCount != null) {
            stmt.bindLong(15, copyCount);
        }
 
        List weeks = entity.getWeeks();
        if (weeks != null) {
            stmt.bindString(16, weeksConverter.convertToDatabaseValue(weeks));
        }
 
        List plans = entity.getPlans();
        if (plans != null) {
            stmt.bindString(17, plansConverter.convertToDatabaseValue(plans));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DateEvent readEntity(Cursor cursor, int offset) {
        DateEvent entity = new DateEvent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.getInt(offset + 2), // type
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // title
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // dayLong
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // dayLongStr
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // explain
            cursor.getShort(offset + 7) != 0, // isCountdown
            cursor.getShort(offset + 8) != 0, // isRemind
            cursor.getInt(offset + 9), // remindDay
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10), // startTime
            cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11), // endTime
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // startTimeStr
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // endTimeStr
            cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14), // copyCount
            cursor.isNull(offset + 15) ? null : weeksConverter.convertToEntityProperty(cursor.getString(offset + 15)), // weeks
            cursor.isNull(offset + 16) ? null : plansConverter.convertToEntityProperty(cursor.getString(offset + 16)) // plans
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DateEvent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setType(cursor.getInt(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDayLong(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setDayLongStr(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setExplain(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIsCountdown(cursor.getShort(offset + 7) != 0);
        entity.setIsRemind(cursor.getShort(offset + 8) != 0);
        entity.setRemindDay(cursor.getInt(offset + 9));
        entity.setStartTime(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
        entity.setEndTime(cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11));
        entity.setStartTimeStr(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setEndTimeStr(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setCopyCount(cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14));
        entity.setWeeks(cursor.isNull(offset + 15) ? null : weeksConverter.convertToEntityProperty(cursor.getString(offset + 15)));
        entity.setPlans(cursor.isNull(offset + 16) ? null : plansConverter.convertToEntityProperty(cursor.getString(offset + 16)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DateEvent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DateEvent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DateEvent entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
