package com.bll.lnkstudy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkstudy.utils.greendao.DateLongConverter;
import com.bll.lnkstudy.utils.greendao.DatePlanConverter;
import com.bll.lnkstudy.utils.greendao.DateWeekConverter;
import java.util.List;

import com.bll.lnkstudy.mvp.model.date.DateEventBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DATE_EVENT_BEAN".
*/
public class DateEventBeanDao extends AbstractDao<DateEventBean, Long> {

    public static final String TABLENAME = "DATE_EVENT_BEAN";

    /**
     * Properties of entity DateEventBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property Type = new Property(2, int.class, "type", false, "TYPE");
        public final static Property Date = new Property(3, int.class, "date", false, "DATE");
        public final static Property Title = new Property(4, String.class, "title", false, "TITLE");
        public final static Property DayLong = new Property(5, long.class, "dayLong", false, "DAY_LONG");
        public final static Property MaxLong = new Property(6, long.class, "maxLong", false, "MAX_LONG");
        public final static Property DayLongStr = new Property(7, String.class, "dayLongStr", false, "DAY_LONG_STR");
        public final static Property Explain = new Property(8, String.class, "explain", false, "EXPLAIN");
        public final static Property IsCountdown = new Property(9, boolean.class, "isCountdown", false, "IS_COUNTDOWN");
        public final static Property IsRemind = new Property(10, boolean.class, "isRemind", false, "IS_REMIND");
        public final static Property RemindDay = new Property(11, int.class, "remindDay", false, "REMIND_DAY");
        public final static Property Weeks = new Property(12, String.class, "weeks", false, "WEEKS");
        public final static Property Plans = new Property(13, String.class, "plans", false, "PLANS");
        public final static Property Dates = new Property(14, String.class, "dates", false, "DATES");
    }

    private final DateWeekConverter weeksConverter = new DateWeekConverter();
    private final DatePlanConverter plansConverter = new DatePlanConverter();
    private final DateLongConverter datesConverter = new DateLongConverter();

    public DateEventBeanDao(DaoConfig config) {
        super(config);
    }
    
    public DateEventBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DATE_EVENT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"TYPE\" INTEGER NOT NULL ," + // 2: type
                "\"DATE\" INTEGER NOT NULL ," + // 3: date
                "\"TITLE\" TEXT," + // 4: title
                "\"DAY_LONG\" INTEGER NOT NULL ," + // 5: dayLong
                "\"MAX_LONG\" INTEGER NOT NULL ," + // 6: maxLong
                "\"DAY_LONG_STR\" TEXT," + // 7: dayLongStr
                "\"EXPLAIN\" TEXT," + // 8: explain
                "\"IS_COUNTDOWN\" INTEGER NOT NULL ," + // 9: isCountdown
                "\"IS_REMIND\" INTEGER NOT NULL ," + // 10: isRemind
                "\"REMIND_DAY\" INTEGER NOT NULL ," + // 11: remindDay
                "\"WEEKS\" TEXT," + // 12: weeks
                "\"PLANS\" TEXT," + // 13: plans
                "\"DATES\" TEXT);"); // 14: dates
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DATE_EVENT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DateEventBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getType());
        stmt.bindLong(4, entity.getDate());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(5, title);
        }
        stmt.bindLong(6, entity.getDayLong());
        stmt.bindLong(7, entity.getMaxLong());
 
        String dayLongStr = entity.getDayLongStr();
        if (dayLongStr != null) {
            stmt.bindString(8, dayLongStr);
        }
 
        String explain = entity.getExplain();
        if (explain != null) {
            stmt.bindString(9, explain);
        }
        stmt.bindLong(10, entity.getIsCountdown() ? 1L: 0L);
        stmt.bindLong(11, entity.getIsRemind() ? 1L: 0L);
        stmt.bindLong(12, entity.getRemindDay());
 
        List weeks = entity.getWeeks();
        if (weeks != null) {
            stmt.bindString(13, weeksConverter.convertToDatabaseValue(weeks));
        }
 
        List plans = entity.getPlans();
        if (plans != null) {
            stmt.bindString(14, plansConverter.convertToDatabaseValue(plans));
        }
 
        List dates = entity.getDates();
        if (dates != null) {
            stmt.bindString(15, datesConverter.convertToDatabaseValue(dates));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DateEventBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getType());
        stmt.bindLong(4, entity.getDate());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(5, title);
        }
        stmt.bindLong(6, entity.getDayLong());
        stmt.bindLong(7, entity.getMaxLong());
 
        String dayLongStr = entity.getDayLongStr();
        if (dayLongStr != null) {
            stmt.bindString(8, dayLongStr);
        }
 
        String explain = entity.getExplain();
        if (explain != null) {
            stmt.bindString(9, explain);
        }
        stmt.bindLong(10, entity.getIsCountdown() ? 1L: 0L);
        stmt.bindLong(11, entity.getIsRemind() ? 1L: 0L);
        stmt.bindLong(12, entity.getRemindDay());
 
        List weeks = entity.getWeeks();
        if (weeks != null) {
            stmt.bindString(13, weeksConverter.convertToDatabaseValue(weeks));
        }
 
        List plans = entity.getPlans();
        if (plans != null) {
            stmt.bindString(14, plansConverter.convertToDatabaseValue(plans));
        }
 
        List dates = entity.getDates();
        if (dates != null) {
            stmt.bindString(15, datesConverter.convertToDatabaseValue(dates));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DateEventBean readEntity(Cursor cursor, int offset) {
        DateEventBean entity = new DateEventBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.getInt(offset + 2), // type
            cursor.getInt(offset + 3), // date
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // title
            cursor.getLong(offset + 5), // dayLong
            cursor.getLong(offset + 6), // maxLong
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // dayLongStr
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // explain
            cursor.getShort(offset + 9) != 0, // isCountdown
            cursor.getShort(offset + 10) != 0, // isRemind
            cursor.getInt(offset + 11), // remindDay
            cursor.isNull(offset + 12) ? null : weeksConverter.convertToEntityProperty(cursor.getString(offset + 12)), // weeks
            cursor.isNull(offset + 13) ? null : plansConverter.convertToEntityProperty(cursor.getString(offset + 13)), // plans
            cursor.isNull(offset + 14) ? null : datesConverter.convertToEntityProperty(cursor.getString(offset + 14)) // dates
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DateEventBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setType(cursor.getInt(offset + 2));
        entity.setDate(cursor.getInt(offset + 3));
        entity.setTitle(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDayLong(cursor.getLong(offset + 5));
        entity.setMaxLong(cursor.getLong(offset + 6));
        entity.setDayLongStr(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setExplain(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setIsCountdown(cursor.getShort(offset + 9) != 0);
        entity.setIsRemind(cursor.getShort(offset + 10) != 0);
        entity.setRemindDay(cursor.getInt(offset + 11));
        entity.setWeeks(cursor.isNull(offset + 12) ? null : weeksConverter.convertToEntityProperty(cursor.getString(offset + 12)));
        entity.setPlans(cursor.isNull(offset + 13) ? null : plansConverter.convertToEntityProperty(cursor.getString(offset + 13)));
        entity.setDates(cursor.isNull(offset + 14) ? null : datesConverter.convertToEntityProperty(cursor.getString(offset + 14)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DateEventBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DateEventBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DateEventBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
