package com.bll.lnkstudy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkstudy.utils.greendao.DatePlanConverter;
import com.bll.lnkstudy.utils.greendao.DateRemindConverter;
import java.util.List;

import com.bll.lnkstudy.mvp.model.DateEvent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DATE_EVENT".
*/
public class DateEventDao extends AbstractDao<DateEvent, Long> {

    public static final String TABLENAME = "DATE_EVENT";

    /**
     * Properties of entity DateEvent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property Type = new Property(2, int.class, "type", false, "TYPE");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property DayLong = new Property(4, Long.class, "dayLong", false, "DAY_LONG");
        public final static Property DayLongStr = new Property(5, String.class, "dayLongStr", false, "DAY_LONG_STR");
        public final static Property Explain = new Property(6, String.class, "explain", false, "EXPLAIN");
        public final static Property StartTime = new Property(7, Long.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(8, Long.class, "endTime", false, "END_TIME");
        public final static Property StartTimeStr = new Property(9, String.class, "startTimeStr", false, "START_TIME_STR");
        public final static Property EndTimeStr = new Property(10, String.class, "endTimeStr", false, "END_TIME_STR");
        public final static Property List = new Property(11, String.class, "list", false, "LIST");
        public final static Property RemindList = new Property(12, String.class, "remindList", false, "REMIND_LIST");
        public final static Property Repeat = new Property(13, String.class, "repeat", false, "REPEAT");
    }

    private final DatePlanConverter listConverter = new DatePlanConverter();
    private final DateRemindConverter remindListConverter = new DateRemindConverter();

    public DateEventDao(DaoConfig config) {
        super(config);
    }
    
    public DateEventDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DATE_EVENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"TYPE\" INTEGER NOT NULL ," + // 2: type
                "\"TITLE\" TEXT," + // 3: title
                "\"DAY_LONG\" INTEGER," + // 4: dayLong
                "\"DAY_LONG_STR\" TEXT," + // 5: dayLongStr
                "\"EXPLAIN\" TEXT," + // 6: explain
                "\"START_TIME\" INTEGER," + // 7: startTime
                "\"END_TIME\" INTEGER," + // 8: endTime
                "\"START_TIME_STR\" TEXT," + // 9: startTimeStr
                "\"END_TIME_STR\" TEXT," + // 10: endTimeStr
                "\"LIST\" TEXT," + // 11: list
                "\"REMIND_LIST\" TEXT," + // 12: remindList
                "\"REPEAT\" TEXT);"); // 13: repeat
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DATE_EVENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DateEvent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getType());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        Long dayLong = entity.getDayLong();
        if (dayLong != null) {
            stmt.bindLong(5, dayLong);
        }
 
        String dayLongStr = entity.getDayLongStr();
        if (dayLongStr != null) {
            stmt.bindString(6, dayLongStr);
        }
 
        String explain = entity.getExplain();
        if (explain != null) {
            stmt.bindString(7, explain);
        }
 
        Long startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindLong(8, startTime);
        }
 
        Long endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(9, endTime);
        }
 
        String startTimeStr = entity.getStartTimeStr();
        if (startTimeStr != null) {
            stmt.bindString(10, startTimeStr);
        }
 
        String endTimeStr = entity.getEndTimeStr();
        if (endTimeStr != null) {
            stmt.bindString(11, endTimeStr);
        }
 
        List list = entity.getList();
        if (list != null) {
            stmt.bindString(12, listConverter.convertToDatabaseValue(list));
        }
 
        List remindList = entity.getRemindList();
        if (remindList != null) {
            stmt.bindString(13, remindListConverter.convertToDatabaseValue(remindList));
        }
 
        String repeat = entity.getRepeat();
        if (repeat != null) {
            stmt.bindString(14, repeat);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DateEvent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getType());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        Long dayLong = entity.getDayLong();
        if (dayLong != null) {
            stmt.bindLong(5, dayLong);
        }
 
        String dayLongStr = entity.getDayLongStr();
        if (dayLongStr != null) {
            stmt.bindString(6, dayLongStr);
        }
 
        String explain = entity.getExplain();
        if (explain != null) {
            stmt.bindString(7, explain);
        }
 
        Long startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindLong(8, startTime);
        }
 
        Long endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(9, endTime);
        }
 
        String startTimeStr = entity.getStartTimeStr();
        if (startTimeStr != null) {
            stmt.bindString(10, startTimeStr);
        }
 
        String endTimeStr = entity.getEndTimeStr();
        if (endTimeStr != null) {
            stmt.bindString(11, endTimeStr);
        }
 
        List list = entity.getList();
        if (list != null) {
            stmt.bindString(12, listConverter.convertToDatabaseValue(list));
        }
 
        List remindList = entity.getRemindList();
        if (remindList != null) {
            stmt.bindString(13, remindListConverter.convertToDatabaseValue(remindList));
        }
 
        String repeat = entity.getRepeat();
        if (repeat != null) {
            stmt.bindString(14, repeat);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DateEvent readEntity(Cursor cursor, int offset) {
        DateEvent entity = new DateEvent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.getInt(offset + 2), // type
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // title
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // dayLong
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // dayLongStr
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // explain
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // startTime
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // endTime
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // startTimeStr
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // endTimeStr
            cursor.isNull(offset + 11) ? null : listConverter.convertToEntityProperty(cursor.getString(offset + 11)), // list
            cursor.isNull(offset + 12) ? null : remindListConverter.convertToEntityProperty(cursor.getString(offset + 12)), // remindList
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13) // repeat
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DateEvent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setType(cursor.getInt(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDayLong(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setDayLongStr(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setExplain(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setStartTime(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setEndTime(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setStartTimeStr(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setEndTimeStr(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setList(cursor.isNull(offset + 11) ? null : listConverter.convertToEntityProperty(cursor.getString(offset + 11)));
        entity.setRemindList(cursor.isNull(offset + 12) ? null : remindListConverter.convertToEntityProperty(cursor.getString(offset + 12)));
        entity.setRepeat(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DateEvent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DateEvent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DateEvent entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
