package com.bll.lnkstudy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkstudy.utils.greendao.StringConverter;
import java.util.List;

import com.bll.lnkstudy.mvp.model.homework.HomeworkPaperBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOMEWORK_PAPER_BEAN".
*/
public class HomeworkPaperBeanDao extends AbstractDao<HomeworkPaperBean, Long> {

    public static final String TABLENAME = "HOMEWORK_PAPER_BEAN";

    /**
     * Properties of entity HomeworkPaperBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property ContentId = new Property(2, int.class, "contentId", false, "CONTENT_ID");
        public final static Property Course = new Property(3, String.class, "course", false, "COURSE");
        public final static Property TypeId = new Property(4, int.class, "typeId", false, "TYPE_ID");
        public final static Property TypeName = new Property(5, String.class, "typeName", false, "TYPE_NAME");
        public final static Property Title = new Property(6, String.class, "title", false, "TITLE");
        public final static Property EndTime = new Property(7, Long.class, "endTime", false, "END_TIME");
        public final static Property StartTime = new Property(8, Long.class, "startTime", false, "START_TIME");
        public final static Property FilePath = new Property(9, String.class, "filePath", false, "FILE_PATH");
        public final static Property Paths = new Property(10, String.class, "paths", false, "PATHS");
        public final static Property DrawPaths = new Property(11, String.class, "drawPaths", false, "DRAW_PATHS");
        public final static Property Page = new Property(12, int.class, "page", false, "PAGE");
        public final static Property State = new Property(13, int.class, "state", false, "STATE");
        public final static Property CorrectMode = new Property(14, int.class, "correctMode", false, "CORRECT_MODE");
        public final static Property Score = new Property(15, int.class, "score", false, "SCORE");
        public final static Property CorrectJson = new Property(16, String.class, "correctJson", false, "CORRECT_JSON");
        public final static Property IsSelfCorrect = new Property(17, boolean.class, "isSelfCorrect", false, "IS_SELF_CORRECT");
        public final static Property ScoreMode = new Property(18, int.class, "scoreMode", false, "SCORE_MODE");
        public final static Property AnswerUrl = new Property(19, String.class, "answerUrl", false, "ANSWER_URL");
        public final static Property CommitJson = new Property(20, String.class, "commitJson", false, "COMMIT_JSON");
    }

    private final StringConverter pathsConverter = new StringConverter();
    private final StringConverter drawPathsConverter = new StringConverter();

    public HomeworkPaperBeanDao(DaoConfig config) {
        super(config);
    }
    
    public HomeworkPaperBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOMEWORK_PAPER_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"CONTENT_ID\" INTEGER NOT NULL UNIQUE ," + // 2: contentId
                "\"COURSE\" TEXT," + // 3: course
                "\"TYPE_ID\" INTEGER NOT NULL ," + // 4: typeId
                "\"TYPE_NAME\" TEXT," + // 5: typeName
                "\"TITLE\" TEXT," + // 6: title
                "\"END_TIME\" INTEGER," + // 7: endTime
                "\"START_TIME\" INTEGER," + // 8: startTime
                "\"FILE_PATH\" TEXT," + // 9: filePath
                "\"PATHS\" TEXT," + // 10: paths
                "\"DRAW_PATHS\" TEXT," + // 11: drawPaths
                "\"PAGE\" INTEGER NOT NULL ," + // 12: page
                "\"STATE\" INTEGER NOT NULL ," + // 13: state
                "\"CORRECT_MODE\" INTEGER NOT NULL ," + // 14: correctMode
                "\"SCORE\" INTEGER NOT NULL ," + // 15: score
                "\"CORRECT_JSON\" TEXT," + // 16: correctJson
                "\"IS_SELF_CORRECT\" INTEGER NOT NULL ," + // 17: isSelfCorrect
                "\"SCORE_MODE\" INTEGER NOT NULL ," + // 18: scoreMode
                "\"ANSWER_URL\" TEXT," + // 19: answerUrl
                "\"COMMIT_JSON\" TEXT);"); // 20: commitJson
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOMEWORK_PAPER_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HomeworkPaperBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getContentId());
 
        String course = entity.getCourse();
        if (course != null) {
            stmt.bindString(4, course);
        }
        stmt.bindLong(5, entity.getTypeId());
 
        String typeName = entity.getTypeName();
        if (typeName != null) {
            stmt.bindString(6, typeName);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(7, title);
        }
 
        Long endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(8, endTime);
        }
 
        Long startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindLong(9, startTime);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(10, filePath);
        }
 
        List paths = entity.getPaths();
        if (paths != null) {
            stmt.bindString(11, pathsConverter.convertToDatabaseValue(paths));
        }
 
        List drawPaths = entity.getDrawPaths();
        if (drawPaths != null) {
            stmt.bindString(12, drawPathsConverter.convertToDatabaseValue(drawPaths));
        }
        stmt.bindLong(13, entity.getPage());
        stmt.bindLong(14, entity.getState());
        stmt.bindLong(15, entity.getCorrectMode());
        stmt.bindLong(16, entity.getScore());
 
        String correctJson = entity.getCorrectJson();
        if (correctJson != null) {
            stmt.bindString(17, correctJson);
        }
        stmt.bindLong(18, entity.getIsSelfCorrect() ? 1L: 0L);
        stmt.bindLong(19, entity.getScoreMode());
 
        String answerUrl = entity.getAnswerUrl();
        if (answerUrl != null) {
            stmt.bindString(20, answerUrl);
        }
 
        String commitJson = entity.getCommitJson();
        if (commitJson != null) {
            stmt.bindString(21, commitJson);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HomeworkPaperBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getContentId());
 
        String course = entity.getCourse();
        if (course != null) {
            stmt.bindString(4, course);
        }
        stmt.bindLong(5, entity.getTypeId());
 
        String typeName = entity.getTypeName();
        if (typeName != null) {
            stmt.bindString(6, typeName);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(7, title);
        }
 
        Long endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(8, endTime);
        }
 
        Long startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindLong(9, startTime);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(10, filePath);
        }
 
        List paths = entity.getPaths();
        if (paths != null) {
            stmt.bindString(11, pathsConverter.convertToDatabaseValue(paths));
        }
 
        List drawPaths = entity.getDrawPaths();
        if (drawPaths != null) {
            stmt.bindString(12, drawPathsConverter.convertToDatabaseValue(drawPaths));
        }
        stmt.bindLong(13, entity.getPage());
        stmt.bindLong(14, entity.getState());
        stmt.bindLong(15, entity.getCorrectMode());
        stmt.bindLong(16, entity.getScore());
 
        String correctJson = entity.getCorrectJson();
        if (correctJson != null) {
            stmt.bindString(17, correctJson);
        }
        stmt.bindLong(18, entity.getIsSelfCorrect() ? 1L: 0L);
        stmt.bindLong(19, entity.getScoreMode());
 
        String answerUrl = entity.getAnswerUrl();
        if (answerUrl != null) {
            stmt.bindString(20, answerUrl);
        }
 
        String commitJson = entity.getCommitJson();
        if (commitJson != null) {
            stmt.bindString(21, commitJson);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HomeworkPaperBean readEntity(Cursor cursor, int offset) {
        HomeworkPaperBean entity = new HomeworkPaperBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.getInt(offset + 2), // contentId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // course
            cursor.getInt(offset + 4), // typeId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // typeName
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // title
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // endTime
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // startTime
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // filePath
            cursor.isNull(offset + 10) ? null : pathsConverter.convertToEntityProperty(cursor.getString(offset + 10)), // paths
            cursor.isNull(offset + 11) ? null : drawPathsConverter.convertToEntityProperty(cursor.getString(offset + 11)), // drawPaths
            cursor.getInt(offset + 12), // page
            cursor.getInt(offset + 13), // state
            cursor.getInt(offset + 14), // correctMode
            cursor.getInt(offset + 15), // score
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // correctJson
            cursor.getShort(offset + 17) != 0, // isSelfCorrect
            cursor.getInt(offset + 18), // scoreMode
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // answerUrl
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20) // commitJson
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HomeworkPaperBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setContentId(cursor.getInt(offset + 2));
        entity.setCourse(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTypeId(cursor.getInt(offset + 4));
        entity.setTypeName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTitle(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setEndTime(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setStartTime(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setFilePath(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setPaths(cursor.isNull(offset + 10) ? null : pathsConverter.convertToEntityProperty(cursor.getString(offset + 10)));
        entity.setDrawPaths(cursor.isNull(offset + 11) ? null : drawPathsConverter.convertToEntityProperty(cursor.getString(offset + 11)));
        entity.setPage(cursor.getInt(offset + 12));
        entity.setState(cursor.getInt(offset + 13));
        entity.setCorrectMode(cursor.getInt(offset + 14));
        entity.setScore(cursor.getInt(offset + 15));
        entity.setCorrectJson(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setIsSelfCorrect(cursor.getShort(offset + 17) != 0);
        entity.setScoreMode(cursor.getInt(offset + 18));
        entity.setAnswerUrl(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setCommitJson(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HomeworkPaperBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HomeworkPaperBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HomeworkPaperBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
