package com.bll.lnkstudy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkstudy.mvp.model.HomeworkType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOMEWORK_TYPE".
*/
public class HomeworkTypeDao extends AbstractDao<HomeworkType, Long> {

    public static final String TABLENAME = "HOMEWORK_TYPE";

    /**
     * Properties of entity HomeworkType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property TypeId = new Property(3, int.class, "typeId", false, "TYPE_ID");
        public final static Property State = new Property(4, int.class, "state", false, "STATE");
        public final static Property Date = new Property(5, long.class, "date", false, "DATE");
        public final static Property ContentResId = new Property(6, String.class, "contentResId", false, "CONTENT_RES_ID");
        public final static Property BgResId = new Property(7, String.class, "bgResId", false, "BG_RES_ID");
        public final static Property CourseId = new Property(8, int.class, "courseId", false, "COURSE_ID");
        public final static Property IsCreate = new Property(9, boolean.class, "isCreate", false, "IS_CREATE");
    }


    public HomeworkTypeDao(DaoConfig config) {
        super(config);
    }
    
    public HomeworkTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOMEWORK_TYPE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"NAME\" TEXT," + // 2: name
                "\"TYPE_ID\" INTEGER NOT NULL ," + // 3: typeId
                "\"STATE\" INTEGER NOT NULL ," + // 4: state
                "\"DATE\" INTEGER NOT NULL ," + // 5: date
                "\"CONTENT_RES_ID\" TEXT," + // 6: contentResId
                "\"BG_RES_ID\" TEXT," + // 7: bgResId
                "\"COURSE_ID\" INTEGER NOT NULL ," + // 8: courseId
                "\"IS_CREATE\" INTEGER NOT NULL );"); // 9: isCreate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOMEWORK_TYPE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HomeworkType entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
        stmt.bindLong(4, entity.getTypeId());
        stmt.bindLong(5, entity.getState());
        stmt.bindLong(6, entity.getDate());
 
        String contentResId = entity.getContentResId();
        if (contentResId != null) {
            stmt.bindString(7, contentResId);
        }
 
        String bgResId = entity.getBgResId();
        if (bgResId != null) {
            stmt.bindString(8, bgResId);
        }
        stmt.bindLong(9, entity.getCourseId());
        stmt.bindLong(10, entity.getIsCreate() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HomeworkType entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
        stmt.bindLong(4, entity.getTypeId());
        stmt.bindLong(5, entity.getState());
        stmt.bindLong(6, entity.getDate());
 
        String contentResId = entity.getContentResId();
        if (contentResId != null) {
            stmt.bindString(7, contentResId);
        }
 
        String bgResId = entity.getBgResId();
        if (bgResId != null) {
            stmt.bindString(8, bgResId);
        }
        stmt.bindLong(9, entity.getCourseId());
        stmt.bindLong(10, entity.getIsCreate() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HomeworkType readEntity(Cursor cursor, int offset) {
        HomeworkType entity = new HomeworkType( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.getInt(offset + 3), // typeId
            cursor.getInt(offset + 4), // state
            cursor.getLong(offset + 5), // date
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // contentResId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // bgResId
            cursor.getInt(offset + 8), // courseId
            cursor.getShort(offset + 9) != 0 // isCreate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HomeworkType entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTypeId(cursor.getInt(offset + 3));
        entity.setState(cursor.getInt(offset + 4));
        entity.setDate(cursor.getLong(offset + 5));
        entity.setContentResId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBgResId(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCourseId(cursor.getInt(offset + 8));
        entity.setIsCreate(cursor.getShort(offset + 9) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HomeworkType entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HomeworkType entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HomeworkType entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
