package com.bll.lnkstudy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkstudy.mvp.model.homework.HomeworkPaperContentBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOMEWORK_PAPER_CONTENT_BEAN".
*/
public class HomeworkPaperContentBeanDao extends AbstractDao<HomeworkPaperContentBean, Long> {

    public static final String TABLENAME = "HOMEWORK_PAPER_CONTENT_BEAN";

    /**
     * Properties of entity HomeworkPaperContentBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property Course = new Property(2, String.class, "course", false, "COURSE");
        public final static Property TypeId = new Property(3, int.class, "typeId", false, "TYPE_ID");
        public final static Property ContentId = new Property(4, int.class, "contentId", false, "CONTENT_ID");
        public final static Property Path = new Property(5, String.class, "path", false, "PATH");
        public final static Property DrawPath = new Property(6, String.class, "drawPath", false, "DRAW_PATH");
        public final static Property Page = new Property(7, int.class, "page", false, "PAGE");
    }


    public HomeworkPaperContentBeanDao(DaoConfig config) {
        super(config);
    }
    
    public HomeworkPaperContentBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOMEWORK_PAPER_CONTENT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"COURSE\" TEXT," + // 2: course
                "\"TYPE_ID\" INTEGER NOT NULL ," + // 3: typeId
                "\"CONTENT_ID\" INTEGER NOT NULL ," + // 4: contentId
                "\"PATH\" TEXT," + // 5: path
                "\"DRAW_PATH\" TEXT," + // 6: drawPath
                "\"PAGE\" INTEGER NOT NULL );"); // 7: page
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOMEWORK_PAPER_CONTENT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HomeworkPaperContentBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String course = entity.getCourse();
        if (course != null) {
            stmt.bindString(3, course);
        }
        stmt.bindLong(4, entity.getTypeId());
        stmt.bindLong(5, entity.getContentId());
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(6, path);
        }
 
        String drawPath = entity.getDrawPath();
        if (drawPath != null) {
            stmt.bindString(7, drawPath);
        }
        stmt.bindLong(8, entity.getPage());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HomeworkPaperContentBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String course = entity.getCourse();
        if (course != null) {
            stmt.bindString(3, course);
        }
        stmt.bindLong(4, entity.getTypeId());
        stmt.bindLong(5, entity.getContentId());
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(6, path);
        }
 
        String drawPath = entity.getDrawPath();
        if (drawPath != null) {
            stmt.bindString(7, drawPath);
        }
        stmt.bindLong(8, entity.getPage());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HomeworkPaperContentBean readEntity(Cursor cursor, int offset) {
        HomeworkPaperContentBean entity = new HomeworkPaperContentBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // course
            cursor.getInt(offset + 3), // typeId
            cursor.getInt(offset + 4), // contentId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // path
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // drawPath
            cursor.getInt(offset + 7) // page
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HomeworkPaperContentBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setCourse(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTypeId(cursor.getInt(offset + 3));
        entity.setContentId(cursor.getInt(offset + 4));
        entity.setPath(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDrawPath(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPage(cursor.getInt(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HomeworkPaperContentBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HomeworkPaperContentBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HomeworkPaperContentBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
