package com.bll.lnkstudy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkstudy.mvp.model.HomeworkContent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOMEWORK_CONTENT".
*/
public class HomeworkContentDao extends AbstractDao<HomeworkContent, Long> {

    public static final String TABLENAME = "HOMEWORK_CONTENT";

    /**
     * Properties of entity HomeworkContent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property BgResId = new Property(2, String.class, "bgResId", false, "BG_RES_ID");
        public final static Property CourseId = new Property(3, int.class, "courseId", false, "COURSE_ID");
        public final static Property HomeworkTypeId = new Property(4, int.class, "homeworkTypeId", false, "HOMEWORK_TYPE_ID");
        public final static Property HomeworkId = new Property(5, long.class, "homeworkId", false, "HOMEWORK_ID");
        public final static Property Date = new Property(6, long.class, "date", false, "DATE");
        public final static Property Path = new Property(7, String.class, "path", false, "PATH");
        public final static Property Page = new Property(8, int.class, "page", false, "PAGE");
    }


    public HomeworkContentDao(DaoConfig config) {
        super(config);
    }
    
    public HomeworkContentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOMEWORK_CONTENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"BG_RES_ID\" TEXT," + // 2: bgResId
                "\"COURSE_ID\" INTEGER NOT NULL ," + // 3: courseId
                "\"HOMEWORK_TYPE_ID\" INTEGER NOT NULL ," + // 4: homeworkTypeId
                "\"HOMEWORK_ID\" INTEGER NOT NULL ," + // 5: homeworkId
                "\"DATE\" INTEGER NOT NULL ," + // 6: date
                "\"PATH\" TEXT," + // 7: path
                "\"PAGE\" INTEGER NOT NULL );"); // 8: page
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOMEWORK_CONTENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HomeworkContent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String bgResId = entity.getBgResId();
        if (bgResId != null) {
            stmt.bindString(3, bgResId);
        }
        stmt.bindLong(4, entity.getCourseId());
        stmt.bindLong(5, entity.getHomeworkTypeId());
        stmt.bindLong(6, entity.getHomeworkId());
        stmt.bindLong(7, entity.getDate());
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(8, path);
        }
        stmt.bindLong(9, entity.getPage());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HomeworkContent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String bgResId = entity.getBgResId();
        if (bgResId != null) {
            stmt.bindString(3, bgResId);
        }
        stmt.bindLong(4, entity.getCourseId());
        stmt.bindLong(5, entity.getHomeworkTypeId());
        stmt.bindLong(6, entity.getHomeworkId());
        stmt.bindLong(7, entity.getDate());
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(8, path);
        }
        stmt.bindLong(9, entity.getPage());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HomeworkContent readEntity(Cursor cursor, int offset) {
        HomeworkContent entity = new HomeworkContent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // bgResId
            cursor.getInt(offset + 3), // courseId
            cursor.getInt(offset + 4), // homeworkTypeId
            cursor.getLong(offset + 5), // homeworkId
            cursor.getLong(offset + 6), // date
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // path
            cursor.getInt(offset + 8) // page
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HomeworkContent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setBgResId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCourseId(cursor.getInt(offset + 3));
        entity.setHomeworkTypeId(cursor.getInt(offset + 4));
        entity.setHomeworkId(cursor.getLong(offset + 5));
        entity.setDate(cursor.getLong(offset + 6));
        entity.setPath(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPage(cursor.getInt(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HomeworkContent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HomeworkContent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HomeworkContent entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
