package com.bll.lnkstudy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkstudy.mvp.model.ItemTypeBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ITEM_TYPE_BEAN".
*/
public class ItemTypeBeanDao extends AbstractDao<ItemTypeBean, Long> {

    public static final String TABLENAME = "ITEM_TYPE_BEAN";

    /**
     * Properties of entity ItemTypeBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Type = new Property(3, int.class, "type", false, "TYPE");
        public final static Property Date = new Property(4, long.class, "date", false, "DATE");
        public final static Property Path = new Property(5, String.class, "path", false, "PATH");
        public final static Property Grade = new Property(6, int.class, "grade", false, "GRADE");
        public final static Property TypeId = new Property(7, int.class, "typeId", false, "TYPE_ID");
        public final static Property IsNew = new Property(8, boolean.class, "isNew", false, "IS_NEW");
    }


    public ItemTypeBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ItemTypeBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ITEM_TYPE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"TITLE\" TEXT," + // 2: title
                "\"TYPE\" INTEGER NOT NULL ," + // 3: type
                "\"DATE\" INTEGER NOT NULL ," + // 4: date
                "\"PATH\" TEXT," + // 5: path
                "\"GRADE\" INTEGER NOT NULL ," + // 6: grade
                "\"TYPE_ID\" INTEGER NOT NULL ," + // 7: typeId
                "\"IS_NEW\" INTEGER NOT NULL );"); // 8: isNew
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ITEM_TYPE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ItemTypeBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
        stmt.bindLong(4, entity.getType());
        stmt.bindLong(5, entity.getDate());
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(6, path);
        }
        stmt.bindLong(7, entity.getGrade());
        stmt.bindLong(8, entity.getTypeId());
        stmt.bindLong(9, entity.getIsNew() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ItemTypeBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
        stmt.bindLong(4, entity.getType());
        stmt.bindLong(5, entity.getDate());
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(6, path);
        }
        stmt.bindLong(7, entity.getGrade());
        stmt.bindLong(8, entity.getTypeId());
        stmt.bindLong(9, entity.getIsNew() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ItemTypeBean readEntity(Cursor cursor, int offset) {
        ItemTypeBean entity = new ItemTypeBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.getInt(offset + 3), // type
            cursor.getLong(offset + 4), // date
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // path
            cursor.getInt(offset + 6), // grade
            cursor.getInt(offset + 7), // typeId
            cursor.getShort(offset + 8) != 0 // isNew
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ItemTypeBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setType(cursor.getInt(offset + 3));
        entity.setDate(cursor.getLong(offset + 4));
        entity.setPath(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setGrade(cursor.getInt(offset + 6));
        entity.setTypeId(cursor.getInt(offset + 7));
        entity.setIsNew(cursor.getShort(offset + 8) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ItemTypeBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ItemTypeBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ItemTypeBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
