package com.bll.lnkstudy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkstudy.mvp.model.NoteContentBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NOTE_CONTENT_BEAN".
*/
public class NoteContentBeanDao extends AbstractDao<NoteContentBean, Long> {

    public static final String TABLENAME = "NOTE_CONTENT_BEAN";

    /**
     * Properties of entity NoteContentBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property Type = new Property(2, int.class, "type", false, "TYPE");
        public final static Property NotebookId = new Property(3, long.class, "notebookId", false, "NOTEBOOK_ID");
        public final static Property Date = new Property(4, long.class, "date", false, "DATE");
        public final static Property Title = new Property(5, String.class, "title", false, "TITLE");
        public final static Property ResId = new Property(6, String.class, "resId", false, "RES_ID");
        public final static Property FolderPath = new Property(7, String.class, "folderPath", false, "FOLDER_PATH");
        public final static Property FilePath = new Property(8, String.class, "filePath", false, "FILE_PATH");
        public final static Property PathName = new Property(9, String.class, "pathName", false, "PATH_NAME");
        public final static Property Page = new Property(10, int.class, "page", false, "PAGE");
    }


    public NoteContentBeanDao(DaoConfig config) {
        super(config);
    }
    
    public NoteContentBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NOTE_CONTENT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"TYPE\" INTEGER NOT NULL ," + // 2: type
                "\"NOTEBOOK_ID\" INTEGER NOT NULL ," + // 3: notebookId
                "\"DATE\" INTEGER NOT NULL ," + // 4: date
                "\"TITLE\" TEXT," + // 5: title
                "\"RES_ID\" TEXT," + // 6: resId
                "\"FOLDER_PATH\" TEXT," + // 7: folderPath
                "\"FILE_PATH\" TEXT," + // 8: filePath
                "\"PATH_NAME\" TEXT," + // 9: pathName
                "\"PAGE\" INTEGER NOT NULL );"); // 10: page
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NOTE_CONTENT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NoteContentBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getType());
        stmt.bindLong(4, entity.getNotebookId());
        stmt.bindLong(5, entity.getDate());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
 
        String resId = entity.getResId();
        if (resId != null) {
            stmt.bindString(7, resId);
        }
 
        String folderPath = entity.getFolderPath();
        if (folderPath != null) {
            stmt.bindString(8, folderPath);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(9, filePath);
        }
 
        String pathName = entity.getPathName();
        if (pathName != null) {
            stmt.bindString(10, pathName);
        }
        stmt.bindLong(11, entity.getPage());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NoteContentBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getType());
        stmt.bindLong(4, entity.getNotebookId());
        stmt.bindLong(5, entity.getDate());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
 
        String resId = entity.getResId();
        if (resId != null) {
            stmt.bindString(7, resId);
        }
 
        String folderPath = entity.getFolderPath();
        if (folderPath != null) {
            stmt.bindString(8, folderPath);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(9, filePath);
        }
 
        String pathName = entity.getPathName();
        if (pathName != null) {
            stmt.bindString(10, pathName);
        }
        stmt.bindLong(11, entity.getPage());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public NoteContentBean readEntity(Cursor cursor, int offset) {
        NoteContentBean entity = new NoteContentBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.getInt(offset + 2), // type
            cursor.getLong(offset + 3), // notebookId
            cursor.getLong(offset + 4), // date
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // title
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // resId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // folderPath
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // filePath
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // pathName
            cursor.getInt(offset + 10) // page
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NoteContentBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setType(cursor.getInt(offset + 2));
        entity.setNotebookId(cursor.getLong(offset + 3));
        entity.setDate(cursor.getLong(offset + 4));
        entity.setTitle(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setResId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setFolderPath(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setFilePath(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setPathName(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setPage(cursor.getInt(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NoteContentBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NoteContentBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NoteContentBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
