package com.bll.lnkstudy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkstudy.mvp.model.NotebookBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NOTEBOOK_BEAN".
*/
public class NotebookBeanDao extends AbstractDao<NotebookBean, Long> {

    public static final String TABLENAME = "NOTEBOOK_BEAN";

    /**
     * Properties of entity NotebookBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property TypeStr = new Property(3, String.class, "typeStr", false, "TYPE_STR");
        public final static Property CreateDate = new Property(4, long.class, "createDate", false, "CREATE_DATE");
        public final static Property ContentResId = new Property(5, String.class, "contentResId", false, "CONTENT_RES_ID");
        public final static Property IsEncrypt = new Property(6, boolean.class, "isEncrypt", false, "IS_ENCRYPT");
        public final static Property Encrypt = new Property(7, String.class, "encrypt", false, "ENCRYPT");
        public final static Property Grade = new Property(8, int.class, "grade", false, "GRADE");
        public final static Property IsCloud = new Property(9, boolean.class, "isCloud", false, "IS_CLOUD");
        public final static Property CloudId = new Property(10, int.class, "cloudId", false, "CLOUD_ID");
    }


    public NotebookBeanDao(DaoConfig config) {
        super(config);
    }
    
    public NotebookBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NOTEBOOK_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"TITLE\" TEXT," + // 2: title
                "\"TYPE_STR\" TEXT," + // 3: typeStr
                "\"CREATE_DATE\" INTEGER NOT NULL ," + // 4: createDate
                "\"CONTENT_RES_ID\" TEXT," + // 5: contentResId
                "\"IS_ENCRYPT\" INTEGER NOT NULL ," + // 6: isEncrypt
                "\"ENCRYPT\" TEXT," + // 7: encrypt
                "\"GRADE\" INTEGER NOT NULL ," + // 8: grade
                "\"IS_CLOUD\" INTEGER NOT NULL ," + // 9: isCloud
                "\"CLOUD_ID\" INTEGER NOT NULL );"); // 10: cloudId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NOTEBOOK_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NotebookBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String typeStr = entity.getTypeStr();
        if (typeStr != null) {
            stmt.bindString(4, typeStr);
        }
        stmt.bindLong(5, entity.getCreateDate());
 
        String contentResId = entity.getContentResId();
        if (contentResId != null) {
            stmt.bindString(6, contentResId);
        }
        stmt.bindLong(7, entity.getIsEncrypt() ? 1L: 0L);
 
        String encrypt = entity.getEncrypt();
        if (encrypt != null) {
            stmt.bindString(8, encrypt);
        }
        stmt.bindLong(9, entity.getGrade());
        stmt.bindLong(10, entity.getIsCloud() ? 1L: 0L);
        stmt.bindLong(11, entity.getCloudId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NotebookBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String typeStr = entity.getTypeStr();
        if (typeStr != null) {
            stmt.bindString(4, typeStr);
        }
        stmt.bindLong(5, entity.getCreateDate());
 
        String contentResId = entity.getContentResId();
        if (contentResId != null) {
            stmt.bindString(6, contentResId);
        }
        stmt.bindLong(7, entity.getIsEncrypt() ? 1L: 0L);
 
        String encrypt = entity.getEncrypt();
        if (encrypt != null) {
            stmt.bindString(8, encrypt);
        }
        stmt.bindLong(9, entity.getGrade());
        stmt.bindLong(10, entity.getIsCloud() ? 1L: 0L);
        stmt.bindLong(11, entity.getCloudId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public NotebookBean readEntity(Cursor cursor, int offset) {
        NotebookBean entity = new NotebookBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // typeStr
            cursor.getLong(offset + 4), // createDate
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // contentResId
            cursor.getShort(offset + 6) != 0, // isEncrypt
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // encrypt
            cursor.getInt(offset + 8), // grade
            cursor.getShort(offset + 9) != 0, // isCloud
            cursor.getInt(offset + 10) // cloudId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NotebookBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTypeStr(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCreateDate(cursor.getLong(offset + 4));
        entity.setContentResId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIsEncrypt(cursor.getShort(offset + 6) != 0);
        entity.setEncrypt(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setGrade(cursor.getInt(offset + 8));
        entity.setIsCloud(cursor.getShort(offset + 9) != 0);
        entity.setCloudId(cursor.getInt(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NotebookBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NotebookBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NotebookBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
