package com.bll.lnkstudy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkstudy.mvp.model.paper.PaperBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PAPER_BEAN".
*/
public class PaperBeanDao extends AbstractDao<PaperBean, Long> {

    public static final String TABLENAME = "PAPER_BEAN";

    /**
     * Properties of entity PaperBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property ContentId = new Property(2, int.class, "contentId", false, "CONTENT_ID");
        public final static Property Course = new Property(3, String.class, "course", false, "COURSE");
        public final static Property TypeId = new Property(4, int.class, "typeId", false, "TYPE_ID");
        public final static Property Type = new Property(5, String.class, "type", false, "TYPE");
        public final static Property Title = new Property(6, String.class, "title", false, "TITLE");
        public final static Property Path = new Property(7, String.class, "path", false, "PATH");
        public final static Property Page = new Property(8, int.class, "page", false, "PAGE");
        public final static Property CorrectMode = new Property(9, int.class, "correctMode", false, "CORRECT_MODE");
        public final static Property Score = new Property(10, String.class, "score", false, "SCORE");
        public final static Property CorrectJson = new Property(11, String.class, "correctJson", false, "CORRECT_JSON");
        public final static Property AnswerUrl = new Property(12, String.class, "answerUrl", false, "ANSWER_URL");
        public final static Property ScoreMode = new Property(13, int.class, "scoreMode", false, "SCORE_MODE");
    }


    public PaperBeanDao(DaoConfig config) {
        super(config);
    }
    
    public PaperBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PAPER_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"CONTENT_ID\" INTEGER NOT NULL ," + // 2: contentId
                "\"COURSE\" TEXT," + // 3: course
                "\"TYPE_ID\" INTEGER NOT NULL ," + // 4: typeId
                "\"TYPE\" TEXT," + // 5: type
                "\"TITLE\" TEXT," + // 6: title
                "\"PATH\" TEXT," + // 7: path
                "\"PAGE\" INTEGER NOT NULL ," + // 8: page
                "\"CORRECT_MODE\" INTEGER NOT NULL ," + // 9: correctMode
                "\"SCORE\" TEXT," + // 10: score
                "\"CORRECT_JSON\" TEXT," + // 11: correctJson
                "\"ANSWER_URL\" TEXT," + // 12: answerUrl
                "\"SCORE_MODE\" INTEGER NOT NULL );"); // 13: scoreMode
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PAPER_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PaperBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getContentId());
 
        String course = entity.getCourse();
        if (course != null) {
            stmt.bindString(4, course);
        }
        stmt.bindLong(5, entity.getTypeId());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(6, type);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(7, title);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(8, path);
        }
        stmt.bindLong(9, entity.getPage());
        stmt.bindLong(10, entity.getCorrectMode());
 
        String score = entity.getScore();
        if (score != null) {
            stmt.bindString(11, score);
        }
 
        String correctJson = entity.getCorrectJson();
        if (correctJson != null) {
            stmt.bindString(12, correctJson);
        }
 
        String answerUrl = entity.getAnswerUrl();
        if (answerUrl != null) {
            stmt.bindString(13, answerUrl);
        }
        stmt.bindLong(14, entity.getScoreMode());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PaperBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getContentId());
 
        String course = entity.getCourse();
        if (course != null) {
            stmt.bindString(4, course);
        }
        stmt.bindLong(5, entity.getTypeId());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(6, type);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(7, title);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(8, path);
        }
        stmt.bindLong(9, entity.getPage());
        stmt.bindLong(10, entity.getCorrectMode());
 
        String score = entity.getScore();
        if (score != null) {
            stmt.bindString(11, score);
        }
 
        String correctJson = entity.getCorrectJson();
        if (correctJson != null) {
            stmt.bindString(12, correctJson);
        }
 
        String answerUrl = entity.getAnswerUrl();
        if (answerUrl != null) {
            stmt.bindString(13, answerUrl);
        }
        stmt.bindLong(14, entity.getScoreMode());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PaperBean readEntity(Cursor cursor, int offset) {
        PaperBean entity = new PaperBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.getInt(offset + 2), // contentId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // course
            cursor.getInt(offset + 4), // typeId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // type
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // title
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // path
            cursor.getInt(offset + 8), // page
            cursor.getInt(offset + 9), // correctMode
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // score
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // correctJson
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // answerUrl
            cursor.getInt(offset + 13) // scoreMode
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PaperBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setContentId(cursor.getInt(offset + 2));
        entity.setCourse(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTypeId(cursor.getInt(offset + 4));
        entity.setType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTitle(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPath(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPage(cursor.getInt(offset + 8));
        entity.setCorrectMode(cursor.getInt(offset + 9));
        entity.setScore(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setCorrectJson(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setAnswerUrl(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setScoreMode(cursor.getInt(offset + 13));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PaperBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PaperBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PaperBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
