package com.bll.lnkstudy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkstudy.mvp.model.paper.PaperTypeBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PAPER_TYPE_BEAN".
*/
public class PaperTypeBeanDao extends AbstractDao<PaperTypeBean, Long> {

    public static final String TABLENAME = "PAPER_TYPE_BEAN";

    /**
     * Properties of entity PaperTypeBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property StudentId = new Property(1, long.class, "studentId", false, "STUDENT_ID");
        public final static Property UserId = new Property(2, long.class, "userId", false, "USER_ID");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property TypeId = new Property(4, int.class, "typeId", false, "TYPE_ID");
        public final static Property Course = new Property(5, String.class, "course", false, "COURSE");
        public final static Property Date = new Property(6, long.class, "date", false, "DATE");
        public final static Property Grade = new Property(7, int.class, "grade", false, "GRADE");
        public final static Property IsCloud = new Property(8, boolean.class, "isCloud", false, "IS_CLOUD");
        public final static Property CloudId = new Property(9, int.class, "cloudId", false, "CLOUD_ID");
    }


    public PaperTypeBeanDao(DaoConfig config) {
        super(config);
    }
    
    public PaperTypeBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PAPER_TYPE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"STUDENT_ID\" INTEGER NOT NULL ," + // 1: studentId
                "\"USER_ID\" INTEGER NOT NULL ," + // 2: userId
                "\"NAME\" TEXT," + // 3: name
                "\"TYPE_ID\" INTEGER NOT NULL UNIQUE ," + // 4: typeId
                "\"COURSE\" TEXT," + // 5: course
                "\"DATE\" INTEGER NOT NULL ," + // 6: date
                "\"GRADE\" INTEGER NOT NULL ," + // 7: grade
                "\"IS_CLOUD\" INTEGER NOT NULL ," + // 8: isCloud
                "\"CLOUD_ID\" INTEGER NOT NULL );"); // 9: cloudId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PAPER_TYPE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PaperTypeBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getStudentId());
        stmt.bindLong(3, entity.getUserId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
        stmt.bindLong(5, entity.getTypeId());
 
        String course = entity.getCourse();
        if (course != null) {
            stmt.bindString(6, course);
        }
        stmt.bindLong(7, entity.getDate());
        stmt.bindLong(8, entity.getGrade());
        stmt.bindLong(9, entity.getIsCloud() ? 1L: 0L);
        stmt.bindLong(10, entity.getCloudId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PaperTypeBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getStudentId());
        stmt.bindLong(3, entity.getUserId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
        stmt.bindLong(5, entity.getTypeId());
 
        String course = entity.getCourse();
        if (course != null) {
            stmt.bindString(6, course);
        }
        stmt.bindLong(7, entity.getDate());
        stmt.bindLong(8, entity.getGrade());
        stmt.bindLong(9, entity.getIsCloud() ? 1L: 0L);
        stmt.bindLong(10, entity.getCloudId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PaperTypeBean readEntity(Cursor cursor, int offset) {
        PaperTypeBean entity = new PaperTypeBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // studentId
            cursor.getLong(offset + 2), // userId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.getInt(offset + 4), // typeId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // course
            cursor.getLong(offset + 6), // date
            cursor.getInt(offset + 7), // grade
            cursor.getShort(offset + 8) != 0, // isCloud
            cursor.getInt(offset + 9) // cloudId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PaperTypeBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStudentId(cursor.getLong(offset + 1));
        entity.setUserId(cursor.getLong(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTypeId(cursor.getInt(offset + 4));
        entity.setCourse(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDate(cursor.getLong(offset + 6));
        entity.setGrade(cursor.getInt(offset + 7));
        entity.setIsCloud(cursor.getShort(offset + 8) != 0);
        entity.setCloudId(cursor.getInt(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PaperTypeBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PaperTypeBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PaperTypeBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
