package com.bll.lnkstudy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkstudy.mvp.model.RecordBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECORD_BEAN".
*/
public class RecordBeanDao extends AbstractDao<RecordBean, Long> {

    public static final String TABLENAME = "RECORD_BEAN";

    /**
     * Properties of entity RecordBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property HomeworkTypeId = new Property(2, int.class, "homeworkTypeId", false, "HOMEWORK_TYPE_ID");
        public final static Property TypeName = new Property(3, String.class, "typeName", false, "TYPE_NAME");
        public final static Property Course = new Property(4, String.class, "course", false, "COURSE");
        public final static Property Title = new Property(5, String.class, "title", false, "TITLE");
        public final static Property ContendId = new Property(6, int.class, "contendId", false, "CONTEND_ID");
        public final static Property Date = new Property(7, long.class, "date", false, "DATE");
        public final static Property Path = new Property(8, String.class, "path", false, "PATH");
        public final static Property Second = new Property(9, int.class, "second", false, "SECOND");
        public final static Property IsHomework = new Property(10, boolean.class, "isHomework", false, "IS_HOMEWORK");
        public final static Property Question = new Property(11, String.class, "question", false, "QUESTION");
        public final static Property Score = new Property(12, double.class, "score", false, "SCORE");
        public final static Property IsCorrect = new Property(13, boolean.class, "isCorrect", false, "IS_CORRECT");
    }


    public RecordBeanDao(DaoConfig config) {
        super(config);
    }
    
    public RecordBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECORD_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"HOMEWORK_TYPE_ID\" INTEGER NOT NULL ," + // 2: homeworkTypeId
                "\"TYPE_NAME\" TEXT," + // 3: typeName
                "\"COURSE\" TEXT," + // 4: course
                "\"TITLE\" TEXT," + // 5: title
                "\"CONTEND_ID\" INTEGER NOT NULL ," + // 6: contendId
                "\"DATE\" INTEGER NOT NULL ," + // 7: date
                "\"PATH\" TEXT," + // 8: path
                "\"SECOND\" INTEGER NOT NULL ," + // 9: second
                "\"IS_HOMEWORK\" INTEGER NOT NULL ," + // 10: isHomework
                "\"QUESTION\" TEXT," + // 11: question
                "\"SCORE\" REAL NOT NULL ," + // 12: score
                "\"IS_CORRECT\" INTEGER NOT NULL );"); // 13: isCorrect
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECORD_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RecordBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getHomeworkTypeId());
 
        String typeName = entity.getTypeName();
        if (typeName != null) {
            stmt.bindString(4, typeName);
        }
 
        String course = entity.getCourse();
        if (course != null) {
            stmt.bindString(5, course);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
        stmt.bindLong(7, entity.getContendId());
        stmt.bindLong(8, entity.getDate());
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(9, path);
        }
        stmt.bindLong(10, entity.getSecond());
        stmt.bindLong(11, entity.getIsHomework() ? 1L: 0L);
 
        String question = entity.getQuestion();
        if (question != null) {
            stmt.bindString(12, question);
        }
        stmt.bindDouble(13, entity.getScore());
        stmt.bindLong(14, entity.getIsCorrect() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RecordBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getHomeworkTypeId());
 
        String typeName = entity.getTypeName();
        if (typeName != null) {
            stmt.bindString(4, typeName);
        }
 
        String course = entity.getCourse();
        if (course != null) {
            stmt.bindString(5, course);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
        stmt.bindLong(7, entity.getContendId());
        stmt.bindLong(8, entity.getDate());
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(9, path);
        }
        stmt.bindLong(10, entity.getSecond());
        stmt.bindLong(11, entity.getIsHomework() ? 1L: 0L);
 
        String question = entity.getQuestion();
        if (question != null) {
            stmt.bindString(12, question);
        }
        stmt.bindDouble(13, entity.getScore());
        stmt.bindLong(14, entity.getIsCorrect() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RecordBean readEntity(Cursor cursor, int offset) {
        RecordBean entity = new RecordBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.getInt(offset + 2), // homeworkTypeId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // typeName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // course
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // title
            cursor.getInt(offset + 6), // contendId
            cursor.getLong(offset + 7), // date
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // path
            cursor.getInt(offset + 9), // second
            cursor.getShort(offset + 10) != 0, // isHomework
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // question
            cursor.getDouble(offset + 12), // score
            cursor.getShort(offset + 13) != 0 // isCorrect
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RecordBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setHomeworkTypeId(cursor.getInt(offset + 2));
        entity.setTypeName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCourse(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTitle(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setContendId(cursor.getInt(offset + 6));
        entity.setDate(cursor.getLong(offset + 7));
        entity.setPath(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSecond(cursor.getInt(offset + 9));
        entity.setIsHomework(cursor.getShort(offset + 10) != 0);
        entity.setQuestion(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setScore(cursor.getDouble(offset + 12));
        entity.setIsCorrect(cursor.getShort(offset + 13) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RecordBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RecordBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RecordBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
